language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
install:
  - pip install -r requirements.txt
  - pip install -r tests-requirements.txt
script: py.test

before_script:
  - psql -c 'create database orator_test;' -U postgres
  - mysql -e 'create database orator_test;'
